name: Publish to PyPI

on:
  release:
    types: [published]  # Trigger only when a GitHub Release is published.

jobs:
  publish:
    if: github.repository == 'cognizant-ai-lab/nsflow'
    name: Build and Publish
    runs-on: ubuntu-latest
    environment: pypi  # Match this to your configured GitHub Environment.
    permissions:
      id-token: write  # Mandatory for PyPI Trusted Publishing

    steps:
      # actions/checkout v6.0.2
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      # cognizant-ai-lab/build-common 1.0.9 -- setup-python-env
      - name: Set up Python and install build tools
        uses: cognizant-ai-lab/build-common/actions/setup-python-env@b14b3de23cb9aca02b2165e57542335e0c8f5304
        with:
          python-version: '3.10'
          requirements-file: ''
          install-extras: 'build'

      - name: Build wheel and sdist
        run: python -m build

      # pypa/gh-action-pypi-publish v1.14.0
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b

      # cognizant-ai-lab/build-common 1.0.9 -- slack-notify
      - name: Notify Slack
        if: ${{ !cancelled() }}
        uses: cognizant-ai-lab/build-common/actions/slack-notify@b14b3de23cb9aca02b2165e57542335e0c8f5304
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
