name: Test

on:
  push:
    branches:
      - main
      - "**"
  pull_request:

permissions:
  contents: read

jobs:
  test:
    if: github.repository == 'cognizant-ai-lab/nsflow'
    # 1.0.9
    uses: cognizant-ai-lab/build-common/.github/workflows/_python-quality-gate.yml@b14b3de23cb9aca02b2165e57542335e0c8f5304
    with:
      python-version: '3.12'
      lint-command-override: |
        set -e
        VIRTUAL_ENV=system make lint-check
      run-shellcheck: false
      run-pytest: true
      test-command-override: 'VIRTUAL_ENV=system PYTHONPATH=.:$PYTHONPATH make test'
      check-readme-pypi: true
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


